### ISSUE TITLE
Dealing with imported types

### ISSUE THREAD

**Issue by janwirth** [dkodaj/decgen#4]
What are the suggested strategies for dealing with imported types?

The CLI I wrote just reads one file.

Should we also get the imported modules and Concatenate them? What strategy do you suggest?

**Comment by dkodaj** [comment]
Sry for the late reply, forgot to watch the repo.

Finding types imported from the app's own modules should not be too hard, we just need to parse the imports. I'll check if some parts of [impfix](https://github.com/dkodaj/impfix) can be reused here.

Types imported from external packages are trickier. E.g. if you import `Math.Vector3.Vec3`, then decgen should find your copy of [elm-explorations/linear-algebra](https://package.elm-lang.org/packages/elm-explorations/linear-algebra/latest) and figure out what to do with it.

**Comment by janwirth** [comment]
Hey any updates? How can I assist?

**Comment by dkodaj** [comment]
Impfix can grab the imports; after that, we only need to feed imported
modules to decgen and look for type definitions as needed. Help is most
welcome on that front, but first I'll have to update impfix to 0.19 and
incorporate elm-parser.

**Comment by janwirth** [comment]
I am using impfix on large 0.19 codebases without issue. Maybe we can use a temporary solution where impfix jsut streams file contents and we can keep impfix like it is?

**Comment by dkodaj** [comment]
Sure, if you're keen to have this working asap. I'll start rewriting decgen
and I'll make suggestions about modifying the cli js.

**Comment by janwirth** [comment]
My plan is to use decgen in https://github.com/FranzSkuffka/iso-elm for the transport layer.

But please do not stress yourself. Let us think about what would create the most value. Maybe we can re-use some code of or contribute to elm-in-elm/compiler. Maybe we can have a call or so to think about what the best strategy is?

**Comment by janwirth** [comment]
Here are the test-suites for the parser: https://github.com/elm-in-elm/compiler/blob/master/tests/ParserTest.elm

**Comment by dkodaj** [comment]
Thanks for the links, your project sounds interesting. Updating is no
stress at all, but give me a few days pls.

**Comment by dkodaj** [comment]
I created a branch named “imports” for this feature. The generator now expects a list of strings. The head is the main module and the tail are the dependencies. The cli takes two arguments, the name of the main module and the (relative) directory where the module is (defaults to cwd).

There's a simple test you can run with

```
$ node src/decgen.js ExampleMain.elm
```

Probably buggy though!

**Comment by janwirth** [comment]
Very cool!

**Comment by FranzSkuffka** [comment]
I think it would be better to pass it a record with two fields: one is the main module and the second the deps. That is more explicit.
