### ISSUE TITLE
Use elm/parser and add unit tests

### ISSUE THREAD

**Issue by janwirth** [dkodaj/decgen#6]
There is an elm-in-elm compiler. They are using elm/parser and only that.

If decgen uses elm/parser we could contribute to and benefit from elm-in-elm/compiler

More info: https://github.com/elm-in-elm/compiler/issues/26

**Comment by dkodaj** [comment]
Thanks for the suggestion, I'll look at elm/parser. It would be nice to get rid of regexes anyway.
